name: Automated Version Branching

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number for the release (e.g., 1.0.0)"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Only Specified Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate  # On Windows, use venv\Scripts\activate
          pip install --upgrade pip
          pip install -r requirements_st.txt
          pip install -r requirements_stplugin.txt

      - name: Generate `requirements-pinned.txt` with Exact Versions
        run: |
          source venv/bin/activate  # Ensure we're in the virtual environment
          pip list --format=freeze | grep -F -f <(cut -d= -f1 requirements_st.txt | sed 's/>.*//g' | sed 's/<.*//g') > requirements_st-pinned.txt
          pip list --format=freeze | grep -F -f <(cut -d= -f1 requirements_stplugin.txt | sed 's/>.*//g' | sed 's/<.*//g') > requirements_stplugin-pinned.txt

      - name: Commit and Push `requirements-pinned.txt`
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b release/v${{ inputs.version }}
          git add requirements_st-pinned.txt requirements_stplugin-pinned.txt
          git commit -m "Generate pinned requirements for v${{ inputs.version }}"
          git push origin release/v${{ inputs.version }}

      - name: Create a Tag for the Version
        run: |
          git tag v${{ inputs.version }}
          git push origin v${{ inputs.version }}
